# Generated by Django 3.2.9 on 2021-11-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='employee_number',
            field=models.IntegerField(unique=True),
        ),
    ]
