# Generated by Django 3.2.9 on 2021-11-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz_name", models.CharField(max_length=254)),
            ],
            options={
                "verbose_name_plural": "Quiz",
            },
        ),
    ]
