# Generated by Django 3.2.9 on 2021-11-04 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=254)),
                ("first_answer", models.CharField(max_length=254)),
                ("second_answer", models.CharField(max_length=254)),
                ("third_answer", models.CharField(max_length=254)),
                ("fourth_answer", models.CharField(max_length=254)),
                ("answer", models.CharField(max_length=254)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Questions",
            },
        ),
    ]
